# Generated by Django 3.2.24 on 2024-03-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plancomment',
            old_name='post',
            new_name='plan',
        ),
    ]
